#!/bin/bash -eux

export MEM_USE_BIG="$(($(grep '^MemTotal:[[:space:]]' /proc/meminfo|awk '{print $2}')*$MEM_PC_BIG/100))"
export MEM_USE_FAST="$(($(grep '^MemTotal:[[:space:]]' /proc/meminfo|awk '{print $2}')*$MEM_PC_FAST/100))"

/usr/local/bin/templater.lua < /etc/aerospike/aerospike.conf.template | tee /etc/aerospike/aerospike.conf

exec /usr/bin/asd --foreground