#!/bin/bash -eux

export MEM_USE="$(($(grep '^MemTotal:[[:space:]]' /proc/meminfo|awk '{print $2}')*$MEM_PC/100))"
export LOCAL_ADDR="$(ip addr show dev eth0|grep -P '^\s*inet\s+'|tr '/' ' '|awk '{print $2}')"

/usr/local/bin/templater.lua < /etc/aerospike/aerospike.conf.template | tee /etc/aerospike/aerospike.conf

exec /usr/bin/asd --foreground